import { restaurantTranslationsEn, safetyLevelLabelsEn } from "@/lib/i18n/dataTranslations";
import type { Language } from "@/lib/i18n/translations";

export type SafetyLevel =
  | "muito_seguro"
  | "seguro"
  | "moderado"
  | "cuidado"
  | "novo"
  | "verificado"
  | "certificado"
  | "recomendado";

export interface Restaurant {
  id: string;
  name: string;
  address: string;
  neighborhood: string;
  city: string;
  rating: number;
  reviewCount: number;
  safetyLevel: SafetyLevel;
  safetyScore: number;
  image: string;
  cuisine: string;
  distance: string;
  isOpen: boolean;
  permanentlyClosed?: boolean;
  openingHours?: string;
  isFavorite: boolean;
  features: string[];
  restrictions?: string[];
  safetyProcedures?: string[];
  description: string;
  dishes: Dish[];
  reviews: Review[];
  phone: string;
  email?: string;
  website?: string;
  instagram?: string;
  chef?: string;
  chefPhoto?: string;
  galleryImages?: string[];
}

export interface DishAdaptation {
  original: string;
  replacement: string;
}

export interface Dish {
  id: string;
  name: string;
  description: string;
  price: number;
  image: string;
  ingredients: string[];
  adaptations?: DishAdaptation[];
  safetyLevel?: SafetyLevel;
  crossContaminationRisk?: "baixo" | "medio" | "alto";
  crossContaminationPrep?: string;
  restrictions?: string[];
  isGlutenFree: boolean;
  isCertified: boolean;
}

export interface Review {
  id: string;
  author: string;
  avatar: string;
  photo?: string;
  rating: number;
  safetyLevel: "muito_seguro" | "seguro" | "moderado" | "nao_seguro";
  contamRisk: "nenhum" | "pequeno" | "alto" | "nao_sei";
  teamKnowledge: "total" | "parcial" | "nao_sabiam" | "nao_perguntei";
  tags?: string[];
  comment: string;
  date: string;
  verified: boolean;
}

export const safetyLevelConfig: Record<SafetyLevel, { label: string; color: string; bg: string; description: string }> = {
  muito_seguro: { label: "Muito seguro", color: "#2E7D32", bg: "#E8F5E9", description: "Cozinha dedicada ao preparo sem glúten (segundo o restaurante)" },
  seguro:       { label: "Mais seguro",  color: "#D97706", bg: "#FEF3C7", description: "Protocolo rigoroso contra contaminação" },
  moderado:     { label: "Atenção",      color: "#E65100", bg: "#FFF3E0", description: "Opções sem glúten disponíveis" },
  cuidado:      { label: "Cuidado",      color: "#B71C1C", bg: "#FFEBEE", description: "Risco de contaminação cruzada" },
  novo:         { label: "Novo",         color: "#C62828", bg: "#FFEBEE", description: "Recém adicionado à comunidade" },
  verificado:   { label: "Verificado",   color: "#6A1B9A", bg: "#F3E5F5", description: "Verificado pela comunidade" },
  certificado:  { label: "Bem avaliado por celíacos",  color: "#00838F", bg: "#E0F7FA", description: "Altamente avaliado pela comunidade celíaca" },
  recomendado:  { label: "Recomendado",  color: "#AD1457", bg: "#FCE4EC", description: "Altamente recomendado" },
};

// Logos reais enviados pelo usuário — mapeados por nome do restaurante.
export const RESTAURANT_LOGOS: Record<string, string> = {
  "Le Manjue Organique": "/Le Manjue Organique.jpg",
  "Haus Hiltl": "/Haus Hiltl.png",
  "Tibits": "/Tibits.png",
  "Marktküche": "/Marktküche.png",
  "Healthy Bites Atelier": "/Healthy Bites Atelier.jpg",
  "Grão Fino": "/grão fino.jpg",
  "Pandan": "/Pandan.jpg",
  "Pizza For Fun": "/Pizza for fun.png",
  "Jampa Nutrileve": "/Jampa Nutrileve.png",
  "Lola Paleo": "/Lola Paleo.jpg",
  "Juro de Dedinho": "/Juro de Dedinho.jpg",
  "Libera": "/libera.jpg",
  "Zufreeden": "/Zufreeden.png",
  "À VIE Baked Goods": "/À VIE Baked Goods.png",
  "Jackie's": "/Jackie's.jpg",
  "Granò": "/Granò.jpg",
};

export const mockRestaurants: Restaurant[] = [
  // ── SÃO PAULO ──────────────────────────────────────────────
  {
    id: "1",
    name: "Le Manjue Organique",
    address: "R. Domingos Fernandes, 608",
    neighborhood: "Vila Nova Conceição",
    city: "São Paulo",
    rating: 4.9,
    reviewCount: 218,
    safetyLevel: "certificado",
    safetyScore: 99,
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&h=400&fit=crop",
    cuisine: "Orgânica / Sem Glúten",
    distance: "0,4 km",
    isOpen: true,
    openingHours: "Seg–Sex 12h–15h · 19h–22h30 · Sáb 12h–23h",
    isFavorite: true,
    features: ["100% sem glúten", "Ingredientes orgânicos", "Certificado ACELBRA"],
    restrictions: ["Sem glúten", "Sem lactose", "Vegano", "Vegetariano"],
    safetyProcedures: [
      "Cozinha dedicada ao preparo sem glúten (segundo o restaurante)",
      "Ingredientes orgânicos certificados",
      "Equipe treinada em doença celíaca",
      "Certificado ACELBRA desde 2015",
    ],
    description:
      "Pioneiro em São Paulo, o Le Manjue é 100% sem glúten e orgânico. Toda a cozinha foi projetada para nunca ter contato com glúten, e os ingredientes são rastreados da fazenda ao prato.",
    phone: "(11) 3034-0631",
    email: "contato@lemanjue.com.br",
    website: "lemanjue.com.br",
    chef: "Aline Tadashi",
    chefPhoto: "https://images.unsplash.com/photo-1577219491135-ce391730fb2c?w=80&h=80&fit=crop&crop=face",
    dishes: [
      {
        id: "d1",
        name: "Risoto de Cogumelos Selvagens",
        description: "Arroz arbóreo com mix de cogumelos, parmesão e trufa negra",
        price: 68.0,
        image: "",
        ingredients: ["Arroz arbóreo", "Cogumelos porcini", "Shiitake", "Parmesão", "Trufa negra", "Vinho branco"],
        safetyLevel: "certificado",
        crossContaminationRisk: "baixo",
        crossContaminationPrep:
          "Preparado em cozinha 100% livre de glúten: panelas, utensílios e bancadas são exclusivos, sem nenhum contato com farinha de trigo ou outros ingredientes com glúten.",
        restrictions: ["Sem glúten", "Vegetariano"],
        isGlutenFree: true,
        isCertified: true,
      },
      {
        id: "d2",
        name: "Tagliatelle de Arroz ao Pesto",
        description: "Massa de arroz artesanal com pesto de manjericão fresco e pinoles",
        price: 58.0,
        image: "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=300&h=200&fit=crop",
        ingredients: ["Farinha de arroz", "Ovos orgânicos", "Manjericão", "Pinoles", "Azeite", "Parmesão"],
        adaptations: [{ original: "Farinha de trigo", replacement: "Farinha de arroz integral" }],
        safetyLevel: "certificado",
        crossContaminationRisk: "baixo",
        crossContaminationPrep:
          "A massa de arroz é feita com utensílios e bancada exclusivos, separados dos ingredientes com glúten. A equipe troca as luvas a cada etapa do preparo.",
        restrictions: ["Sem glúten", "Vegetariano"],
        isGlutenFree: true,
        isCertified: true,
      },
    ],
    reviews: [
      {
        id: "r1",
        author: "Fernanda A.",
        avatar: "FA",
        photo: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=80&h=80&fit=crop&crop=face",
        rating: 5,
        safetyLevel: "muito_seguro",
        contamRisk: "nenhum",
        teamKnowledge: "total",
        tags: ["Sem contaminação", "Equipe bem informada", "Me senti seguro"],
        comment:
          "Frequento há 4 anos. Nunca tive nenhuma reação. A equipe conhece celíaca de verdade, não é só marketing. Prato favorito: o tagliatelle de arroz.",
        date: "15/03/2024",
        verified: true,
      },
      {
        id: "r2",
        author: "Bruno K.",
        avatar: "BK",
        photo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=80&h=80&fit=crop&crop=face",
        rating: 5,
        safetyLevel: "muito_seguro",
        contamRisk: "nenhum",
        teamKnowledge: "total",
        tags: ["Voltaria com certeza", "Cardápio claro"],
        comment: "Levei minha mãe celíaca no aniversário dela. Foi emocionante ela poder comer de tudo no cardápio sem se preocupar!",
        date: "10/03/2024",
        verified: true,
      },
    ],
  },
  // ── ZURIQUE ────────────────────────────────────────────────
  {
    id: "5",
    name: "Haus Hiltl",
    address: "Sihlstrasse, 28",
    neighborhood: "Altstadt",
    city: "Zurique",
    rating: 4.8,
    reviewCount: 304,
    safetyLevel: "certificado",
    safetyScore: 98,
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&h=400&fit=crop",
    cuisine: "Vegetariana / Internacional",
    distance: "3,2 km",
    isOpen: true,
    openingHours: "Seg–Qua 7h–22h · Qui–Sex 7h–23h · Sáb 8h–23h · Dom 10h–22h",
    isFavorite: true,
    features: ["Buffet 100% vegetariano", "Rótulos GF em todos os pratos", "Certificado Swiss GF"],
    restrictions: ["Sem glúten", "Vegano", "Vegetariano", "Sem lactose", "Sem ovos"],
    safetyProcedures: [
      "Todos os pratos GF são claramente identificados",
      "Equipe treinada em alergias alimentares",
      "Certificação Swiss Coeliac Society",
      "Buffet com bandejas separadas por tipo de restrição",
    ],
    description:
      "Fundado em 1898, o Hiltl é o restaurante vegetariano mais antigo do mundo em funcionamento. Seu buffet em Zurique tem identificação clara de alérgenos e dezenas de opções sem glúten certificadas.",
    phone: "+41 44 227 70 00",
    email: "info@hiltl.ch",
    website: "hiltl.ch",
    chef: "Stefan Wiesner",
    chefPhoto: "https://images.unsplash.com/photo-1566554273541-37a9ca77b91f?w=80&h=80&fit=crop&crop=face",
    dishes: [
      {
        id: "d7",
        name: "Rösti com Queijo Raclette",
        description: "Rösti de batata suíço com raclette derretido e picles de pepino",
        price: 24.0,
        image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=300&h=200&fit=crop",
        ingredients: ["Batata", "Raclette suíço", "Manteiga clarificada", "Pepino em conserva", "Cebola caramelizada"],
        safetyLevel: "certificado",
        crossContaminationRisk: "baixo",
        crossContaminationPrep:
          "Preparado em chapa exclusiva, higienizada antes do uso, com utensílios separados para os pratos sem glúten e identificação visual no buffet.",
        restrictions: ["Sem glúten", "Vegetariano"],
        isGlutenFree: true,
        isCertified: true,
      },
      {
        id: "d8",
        name: "Curry de Grão-de-bico",
        description: "Grão-de-bico com leite de coco, especiarias e arroz basmati",
        price: 22.0,
        image: "",
        ingredients: ["Grão-de-bico", "Leite de coco", "Tomate", "Espinafre", "Cúrcuma", "Cominho", "Arroz basmati"],
        safetyLevel: "certificado",
        crossContaminationRisk: "baixo",
        crossContaminationPrep:
          "Cozido em panela exclusiva para pratos sem glúten, com ingredientes pesados e armazenados separadamente dos itens que contêm glúten.",
        restrictions: ["Sem glúten", "Vegano"],
        isGlutenFree: true,
        isCertified: true,
      },
      {
        id: "d11",
        name: "Hiltl Burger",
        description:
          "Hambúrguer vegano à base de proteína vegetal, com alface baby, tomate, cebola roxa, burger sauce e ketchup apimentado, servido no pão brioche tradicional. Opção com queijo suíço disponível.",
        price: 26.0,
        image: "",
        ingredients: ["Hambúrguer vegetal Hiltl", "Pão brioche", "Alface baby", "Tomate", "Cebola roxa", "Burger sauce", "Ketchup apimentado"],
        safetyLevel: "moderado",
        crossContaminationRisk: "medio",
        crossContaminationPrep:
          "O pão brioche tradicional contém glúten. O restaurante pode oferecer pão sem glúten como substituição sob consulta, mas não garante ausência total de contaminação cruzada na cozinha para este item.",
        restrictions: ["Vegano", "Vegetariano"],
        isGlutenFree: false,
        isCertified: false,
      },
    ],
    reviews: [
      {
        id: "r6",
        author: "Lívia F.",
        avatar: "LF",
        photo: "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=80&h=80&fit=crop&crop=face",
        rating: 5,
        safetyLevel: "muito_seguro",
        contamRisk: "nenhum",
        teamKnowledge: "total",
        tags: ["Sem contaminação", "Equipe bem informada", "Me senti seguro"],
        comment:
          "Visitei durante intercâmbio em Zurique. O Hiltl é incrível — cada item do buffet tem etiqueta com alérgenos e a equipe fala sobre celíaca com naturalidade.",
        date: "20/02/2024",
        verified: true,
      },
    ],
  },
  {
    id: "6",
    name: "Tibits",
    address: "Seefeldstrasse, 2",
    neighborhood: "Seefeld",
    city: "Zurique",
    rating: 4.6,
    reviewCount: 241,
    safetyLevel: "muito_seguro",
    safetyScore: 95,
    image: "https://storage.flyo.cloud/30_7de9a720_tibits-aarau-1.png/thumb/800x600?format=webp",
    cuisine: "Vegetariana / Buffet",
    distance: "4,1 km",
    isOpen: true,
    openingHours: "Seg–Qui 6h30–23h · Sex–Sáb 6h30–0h · Dom 9h–23h",
    isFavorite: false,
    features: ["Buffet pago por peso", "GF identificado em cada prato", "Ingredientes sazonais"],
    restrictions: ["Sem glúten", "Vegano", "Vegetariano"],
    safetyProcedures: [
      "Identificação de alérgenos em cada bandeja",
      "Equipe treinada em restrições alimentares",
      "Ingredientes orgânicos e sazonais",
    ],
    description:
      "O Tibits é uma cadeia de buffets vegetarianos suíços com identificação rigorosa de alérgenos. Na unidade de Seefeld, à beira do lago, os pratos sem glúten são claramente marcados.",
    phone: "+41 44 260 32 22",
    email: "info@tibits.ch",
    website: "tibits.ch",
    dishes: [
      {
        id: "d9",
        name: "Salada de Lentilha Puy",
        description: "Lentilhas verdes com vinagrete de mostarda, ervas e legumes crocantes",
        price: 18.0,
        image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=300&h=200&fit=crop",
        ingredients: ["Lentilha Puy", "Cenoura", "Salsão", "Mostarda de Dijon GF", "Vinagre balsâmico", "Salsinha"],
        safetyLevel: "muito_seguro",
        crossContaminationRisk: "baixo",
        crossContaminationPrep:
          "Montada em estação separada do buffet, com utensílios de servir exclusivos e troca de luvas entre as preparações para evitar contato cruzado.",
        restrictions: ["Sem glúten", "Vegano"],
        isGlutenFree: true,
        isCertified: false,
      },
    ],
    reviews: [
      {
        id: "r7",
        author: "André S.",
        avatar: "AS",
        photo: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=80&h=80&fit=crop&crop=face",
        rating: 5,
        safetyLevel: "muito_seguro",
        contamRisk: "nenhum",
        teamKnowledge: "total",
        tags: ["Cardápio claro", "Me senti seguro", "Voltaria com certeza"],
        comment: "Cada prato tem lista de ingredientes e alérgenos. Fui com minha esposa celíaca e ela comeu com total tranquilidade.",
        date: "14/02/2024",
        verified: true,
      },
    ],
  },
  {
    id: "7",
    name: "Marktküche",
    address: "Feldstrasse 98",
    neighborhood: "",
    city: "Zürich",
    rating: 4.5,
    reviewCount: 97,
    safetyLevel: "verificado",
    safetyScore: 88,
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&h=400&fit=crop",
    cuisine: "Europeia Contemporânea",
    distance: "5,0 km",
    isOpen: true,
    openingHours: "Qua–Sex 17h30–23h30 · Sáb 12h–15h · 17h30–23h30",
    isFavorite: false,
    features: ["Menu sazonal", "Pratos GF identificados", "Produtos locais"],
    restrictions: ["Sem glúten", "Pratos adaptáveis"],
    safetyProcedures: [
      "Pratos GF identificados no menu",
      "Chef informado sobre celíaca",
      "Ingredientes locais do mercado semanal",
    ],
    description:
      "Restaurante contemporâneo no bairro histórico de Niederdorf, com menu baseado no mercado semanal local. Pratos sem glúten são identificados e o chef adapta pedidos com aviso prévio.",
    phone: "+41 44 211 22 11",
    email: "info@marktkueche.ch",
    website: "marktkueche.ch",
    chef: "Tobias Hoesli",
    dishes: [
      {
        id: "d10",
        name: "Polenta Cremosa com Funghi",
        description: "Polenta suíça cremosa com mix de cogumelos e ervas frescas",
        price: 28.0,
        image: "",
        ingredients: ["Polenta fina", "Cogumelos porcini", "Chanterelle", "Alho", "Tomilho", "Queijo Sbrinz"],
        safetyLevel: "verificado",
        crossContaminationRisk: "baixo",
        crossContaminationPrep:
          "Preparada em panela exclusiva para pratos sem glúten, com o chef avisado previamente para reforçar o uso de utensílios e tábuas separadas.",
        restrictions: ["Sem glúten", "Vegetariano"],
        isGlutenFree: true,
        isCertified: false,
      },
    ],
    reviews: [
      {
        id: "r8",
        author: "Priya N.",
        avatar: "PN",
        photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop&crop=face",
        rating: 4,
        safetyLevel: "seguro",
        contamRisk: "pequeno",
        teamKnowledge: "parcial",
        tags: ["Cardápio claro", "Ambiente acolhedor"],
        comment: "Experiência muito boa. Avisou ao garçom sobre celíaca e ele foi buscar o chef para confirmar os ingredientes. A polenta é divina.",
        date: "28/01/2024",
        verified: true,
      },
    ],
  },
  // ── HEALTHY BITES ATELIER ─────────────────────────────────────
  {
    id: "healthy-bites-atelier",
    name: "Healthy Bites Atelier",
    address: "",
    neighborhood: "",
    city: "",
    rating: 0,
    reviewCount: 0,
    safetyLevel: "moderado" as SafetyLevel,
    safetyScore: 0,
    image: "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=400&h=300&fit=crop",
    cuisine: "Confeitaria",
    distance: "",
    isOpen: true,
    isFavorite: false,
    features: ["Sem glúten", "Sem lactose", "Sem açúcar", "Fit"],
    restrictions: ["Sem glúten", "Sem lactose", "Sem açúcar"],
    safetyProcedures: [
      "Usa ingredientes sem glúten em produtos específicos",
      "Sem confirmação clara de operação dedicada para celíacos",
    ],
    description: "Confeitaria saudável com doces sem glúten, sem lactose e sem açúcar.",
    phone: "+55 11 99984-9187",
    chef: "Victória Della Manna",
    instagram: "healthybitesatelier",
    dishes: [
      {
        id: "hba-d1",
        name: "Bolo fit de cacau com castanhas",
        description: "",
        price: 0,
        image: "",
        ingredients: [],
        safetyLevel: "moderado" as SafetyLevel,
        crossContaminationRisk: "medio" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: false,
        isCertified: false,
      },
      {
        id: "hba-d2",
        name: "Brownie com calda de avelã",
        description: "",
        price: 0,
        image: "",
        ingredients: [],
        safetyLevel: "moderado" as SafetyLevel,
        crossContaminationRisk: "medio" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: false,
        isCertified: false,
      },
      {
        id: "hba-d3",
        name: "Banoffee fit",
        description: "",
        price: 0,
        image: "",
        ingredients: [],
        safetyLevel: "moderado" as SafetyLevel,
        crossContaminationRisk: "medio" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: false,
        isCertified: false,
      },
      {
        id: "hba-d4",
        name: "Ovos de Páscoa funcionais",
        description: "",
        price: 0,
        image: "https://images.unsplash.com/photo-1615887023701-6adebc4f8a0a?w=300&h=200&fit=crop",
        ingredients: [],
        safetyLevel: "moderado" as SafetyLevel,
        crossContaminationRisk: "medio" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: false,
        isCertified: false,
      },
    ],
    reviews: [],
  },

  // ── GRÃO FINO ─────────────────────────────────────────────────
  {
    id: "grao-fino",
    name: "Grão Fino",
    address: "R. Mário Ferraz, 462",
    neighborhood: "Pinheiros",
    city: "São Paulo",
    rating: 4.7,
    reviewCount: 89,
    safetyLevel: "seguro" as SafetyLevel,
    safetyScore: 90,
    image: "/Grão Fino Fachada.jpg",
    galleryImages: [
      "/Grão Fino Fachada.jpg",
      "https://static.wixstatic.com/media/4614e6_08f73bfc2b4f4152907b2495bb1550a0~mv2.jpg",
      "https://static.wixstatic.com/media/4614e6_94a180dda3d8414c83c89861e6829b05~mv2.jpg",
      "https://static.wixstatic.com/media/4614e6_92e7afedb4a24b69b54066fc799e0890~mv2.jpg",
      "https://static.wixstatic.com/media/4614e6_5cf43de4a4504ce092d799bb3d86b1a1~mv2.jpg",
      "https://static.wixstatic.com/media/4614e6_651639d13e474186bdb16dc37dee509f~mv2.jpg",
    ],
    cuisine: "Padaria / Cafeteria / Restaurante Funcional",
    distance: "",
    isOpen: true,
    isFavorite: false,
    features: ["100% sem glúten", "Sem lactose", "Funcional", "Brunch"],
    restrictions: ["Sem glúten", "Sem lactose"],
    safetyProcedures: [
      "Produção voltada a restrições alimentares",
      "Forte foco em ingredientes alternativos e controle de preparo",
    ],
    description: "Padaria funcional com produção sem glúten e sem lactose, focada em alimentação saudável.",
    phone: "",
    website: "https://www.sougraofino.com.br/",
    instagram: "graofino",
    dishes: [
      {
        id: "grao-fino-d1",
        name: "Pão tipo francês",
        description: "",
        price: 0,
        image: "https://static.wixstatic.com/media/4614e6_03405cb3563f4c609004d49cfa59a3c2~mv2.jpg",
        ingredients: [],
        safetyLevel: "seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: true,
        isCertified: false,
      },
      {
        id: "grao-fino-d2",
        name: "Pão de abóbora",
        description: "",
        price: 0,
        image: "https://static.wixstatic.com/media/4614e6_843df455e0a7454e960b13c86fd4ff6b~mv2.jpg",
        ingredients: [],
        safetyLevel: "seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: true,
        isCertified: false,
      },
      {
        id: "grao-fino-d3",
        name: "Ciabatta sem glúten",
        description: "",
        price: 0,
        image: "https://static.wixstatic.com/media/4614e6_94dbc9739f314e3bbf737e2e2dc03b22~mv2.jpg",
        ingredients: [],
        safetyLevel: "seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: true,
        isCertified: false,
      },
      {
        id: "grao-fino-d4",
        name: "Pão low carb de amêndoas",
        description: "",
        price: 0,
        image: "https://static.wixstatic.com/media/4614e6_0de24878a70f4bca8c2251bb5dccccfc~mv2.jpg",
        ingredients: [],
        safetyLevel: "seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: true,
        isCertified: false,
      },
      {
        id: "grao-fino-d5",
        name: "Tapioca com frango cremoso",
        description: "",
        price: 0,
        image: "https://static.wixstatic.com/media/4614e6_aa455f3756ee4bc18d5e41f7c8fc48a4~mv2.jpg",
        ingredients: [],
        safetyLevel: "seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: true,
        isCertified: false,
      },
      {
        id: "grao-fino-d6",
        name: "Hambúrguer no pão sem glúten",
        description: "",
        price: 0,
        image: "https://static.wixstatic.com/media/4614e6_f2048de6fc494e96bdd50a7e6bcfe1a8~mv2.jpg",
        ingredients: [],
        safetyLevel: "seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: true,
        isCertified: false,
      },
      {
        id: "grao-fino-d7",
        name: "Waffle sem glúten",
        description: "",
        price: 0,
        image: "https://static.wixstatic.com/media/4614e6_92e7afedb4a24b69b54066fc799e0890~mv2.jpg",
        ingredients: [],
        safetyLevel: "seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: true,
        isCertified: false,
      },
    ],
    reviews: [],
  },

  // ── PANDAN ────────────────────────────────────────────────────
  {
    id: "pandan",
    name: "Pandan",
    address: "R. Ferreira de Araújo, 369 - Pinheiros, São Paulo - SP",
    neighborhood: "Pinheiros",
    city: "São Paulo",
    rating: 4.6,
    reviewCount: 530,
    safetyLevel: "seguro" as SafetyLevel,
    safetyScore: 90,
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=300&fit=crop",
    cuisine: "Restaurante / Padaria / Confeitaria",
    distance: "",
    isOpen: true,
    isFavorite: false,
    features: ["100% sem glúten", "Padaria", "Confeitaria", "Comfort food"],
    restrictions: ["Sem glúten"],
    safetyProcedures: [
      "Foco em alimentação segura para celíacos",
      "Proposta dedicada ao público sem glúten",
    ],
    description: "Restaurante e laboratório especializado em alimentos sem glúten, com foco em segurança e acolhimento.",
    phone: "",
    website: "https://pandanlab.com.br/",
    chef: "Daniella Kobayashi",
    instagram: "pandan_sp",
    dishes: [
      {
        id: "pandan-d1",
        name: "Strogonoff de frango com arroz e batata palha",
        description: "",
        price: 0,
        image: "",
        ingredients: [],
        safetyLevel: "seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: true,
        isCertified: false,
      },
      {
        id: "pandan-d2",
        name: "Rondeli de presunto e queijo",
        description: "",
        price: 0,
        image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=300&h=200&fit=crop",
        ingredients: [],
        safetyLevel: "seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: true,
        isCertified: false,
      },
      {
        id: "pandan-d3",
        name: "Sobrecoxa com molho de alecrim e creme de abóbora",
        description: "",
        price: 0,
        image: "https://images.unsplash.com/photo-1598103442097-8b74394b95c7?w=300&h=200&fit=crop",
        ingredients: [],
        safetyLevel: "seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: true,
        isCertified: false,
      },
      {
        id: "pandan-d4",
        name: "Pão francês sem glúten",
        description: "",
        price: 0,
        image: "",
        ingredients: [],
        safetyLevel: "seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: true,
        isCertified: false,
      },
      {
        id: "pandan-d5",
        name: "Brioche sem glúten",
        description: "",
        price: 0,
        image: "",
        ingredients: [],
        safetyLevel: "seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: true,
        isCertified: false,
      },
      {
        id: "pandan-d6",
        name: "Cheesecake com frutas vermelhas",
        description: "",
        price: 0,
        image: "",
        ingredients: [],
        safetyLevel: "seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: true,
        isCertified: false,
      },
    ],
    reviews: [],
  },

  // ── PIZZA FOR FUN ─────────────────────────────────────────────
  {
    id: "pizza-for-fun",
    name: "Pizza For Fun",
    address: "",
    neighborhood: "",
    city: "São Paulo",
    rating: 0,
    reviewCount: 0,
    safetyLevel: "muito_seguro" as SafetyLevel,
    safetyScore: 98,
    image: "https://pizzaforfun.com.br/wp-content/uploads/2025/08/IMG_7765-1200x800.jpg",
    galleryImages: [
      "https://pizzaforfun.com.br/wp-content/uploads/2021/05/Marguerita-For-Fun@2x-1200x853.jpg",
      "https://pizzaforfun.com.br/wp-content/uploads/2021/05/Tre-Fungui-1@2x-1200x853.jpg",
      "https://pizzaforfun.com.br/wp-content/uploads/2021/05/Pero-no-Mucho@2x-1200x853.jpg",
      "https://pizzaforfun.com.br/wp-content/uploads/2025/08/IMG_7765-1200x800.jpg",
      "https://pizzaforfun.com.br/wp-content/themes/pizzaforfun/images/img-sobre-home.png",
    ],
    cuisine: "Pizzaria",
    distance: "",
    isOpen: true,
    isFavorite: false,
    features: ["100% sem glúten", "Sem contaminação cruzada", "Cozinha dedicada"],
    restrictions: ["Sem glúten"],
    safetyProcedures: [
      "Ambiente dedicado, sem entrada de glúten",
      "Comunicação explícita sobre ausência de contaminação cruzada",
    ],
    description: "Pizzaria especializada em pizzas 100% sem glúten.",
    phone: "(11) 3360-8075",
    email: "contato@pizzaforfun.com.br",
    website: "https://pizzaforfun.com.br/",
    chef: "Alessandra Rabello Jordão",
    instagram: "pizzaforfunoficial",
    dishes: [
      {
        id: "pff-d1",
        name: "Marguerita",
        description: "",
        price: 0,
        image: "https://pizzaforfun.com.br/wp-content/uploads/2021/05/Marguerita-For-Fun@2x-1200x853.jpg",
        ingredients: [],
        safetyLevel: "muito_seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: true,
        isCertified: false,
      },
      {
        id: "pff-d2",
        name: "Caprese",
        description: "",
        price: 0,
        image: "https://pizzaforfun.com.br/wp-content/uploads/2021/05/Caprese@2x-1200x853.jpg",
        ingredients: [],
        safetyLevel: "muito_seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: true,
        isCertified: false,
      },
      {
        id: "pff-d3",
        name: "Tre Funghi",
        description: "",
        price: 0,
        image: "https://pizzaforfun.com.br/wp-content/uploads/2021/05/Tre-Fungui-1@2x-1200x853.jpg",
        ingredients: [],
        safetyLevel: "muito_seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: true,
        isCertified: false,
      },
      {
        id: "pff-d4",
        name: "Calabresa",
        description: "",
        price: 0,
        image: "https://pizzaforfun.com.br/wp-content/uploads/2021/05/Pero-no-Mucho@2x-1200x853.jpg",
        ingredients: [],
        safetyLevel: "muito_seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: true,
        isCertified: false,
      },
      {
        id: "pff-d5",
        name: "Bergamo",
        description: "",
        price: 0,
        image: "https://pizzaforfun.com.br/wp-content/uploads/2021/05/Bergamo-2@2x-1200x853.jpg",
        ingredients: [],
        safetyLevel: "muito_seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: true,
        isCertified: false,
      },
      {
        id: "pff-d6",
        name: "Chocolate com banana",
        description: "",
        price: 0,
        image: "https://pizzaforfun.com.br/wp-content/uploads/2021/05/Choccolato-com-Banana@2x-1113x1200.jpg",
        ingredients: [],
        safetyLevel: "muito_seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: true,
        isCertified: false,
      },
    ],
    reviews: [],
  },

  // ── JAMPA NUTRILEVE ───────────────────────────────────────────
  {
    id: "jampa-nutrileve",
    name: "Jampa Nutrileve",
    address: "",
    neighborhood: "",
    city: "João Pessoa",
    rating: 0,
    reviewCount: 0,
    safetyLevel: "muito_seguro" as SafetyLevel,
    safetyScore: 98,
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400&h=300&fit=crop",
    cuisine: "Restaurante / Pizzaria",
    distance: "",
    isOpen: true,
    isFavorite: false,
    features: ["100% sem glúten", "Sem contaminação cruzada", "Inclusivo"],
    restrictions: ["Sem glúten"],
    safetyProcedures: [
      "Comunica operação sem glúten e sem contaminação cruzada",
      "Foco em inclusão alimentar",
    ],
    description: "Restaurante e pizzaria sem glúten, com proposta leve e inclusiva.",
    phone: "",
    instagram: "jampanutrileve",
    dishes: [
      {
        id: "jnl-d1",
        name: "Pizza de camarão",
        description: "",
        price: 0,
        image: "",
        ingredients: [],
        safetyLevel: "muito_seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: true,
        isCertified: false,
      },
      {
        id: "jnl-d2",
        name: "Pizzas grandes sem glúten",
        description: "",
        price: 0,
        image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=300&h=200&fit=crop",
        ingredients: [],
        safetyLevel: "muito_seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: true,
        isCertified: false,
      },
      {
        id: "jnl-d3",
        name: "Pratos proteicos sem farinha",
        description: "",
        price: 0,
        image: "",
        ingredients: [],
        safetyLevel: "muito_seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: true,
        isCertified: false,
      },
      {
        id: "jnl-d4",
        name: "Combos com bebida",
        description: "",
        price: 0,
        image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=300&h=200&fit=crop",
        ingredients: [],
        safetyLevel: "muito_seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: true,
        isCertified: false,
      },
    ],
    reviews: [],
  },

  // ── LOLA PALEO ────────────────────────────────────────────────
  {
    id: "lola-paleo",
    name: "Lola Paleo",
    address: "",
    neighborhood: "Manaíra",
    city: "João Pessoa",
    rating: 4.2,
    reviewCount: 320,
    safetyLevel: "moderado" as SafetyLevel,
    safetyScore: 0,
    image: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=400&h=300&fit=crop",
    cuisine: "Padaria / Confeitaria / Cafeteria Funcional",
    distance: "",
    isOpen: true,
    isFavorite: false,
    features: ["Sem glúten", "Sem lactose", "Sem açúcar", "Paleo"],
    restrictions: ["Sem glúten", "Sem lactose", "Sem açúcar"],
    safetyProcedures: [
      "Boa oferta de produtos sem glúten",
      "Sem comprovação clara de controle rigoroso de contaminação cruzada",
    ],
    description: "Padaria e confeitaria funcional com produtos sem glúten, sem açúcar e sem lactose.",
    phone: "+55 83 99665-5024",
    chef: "Guilherme Castro Nunes Mesquita",
    instagram: "lolapaleo",
    dishes: [
      {
        id: "lp-d1",
        name: "Pães de amêndoas",
        description: "",
        price: 0,
        image: "",
        ingredients: [],
        safetyLevel: "moderado" as SafetyLevel,
        crossContaminationRisk: "medio" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: false,
        isCertified: false,
      },
      {
        id: "lp-d2",
        name: "Pães de pistache",
        description: "",
        price: 0,
        image: "",
        ingredients: [],
        safetyLevel: "moderado" as SafetyLevel,
        crossContaminationRisk: "medio" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: false,
        isCertified: false,
      },
      {
        id: "lp-d3",
        name: "Croissants",
        description: "",
        price: 0,
        image: "",
        ingredients: [],
        safetyLevel: "moderado" as SafetyLevel,
        crossContaminationRisk: "medio" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: false,
        isCertified: false,
      },
      {
        id: "lp-d4",
        name: "Tortas",
        description: "",
        price: 0,
        image: "",
        ingredients: [],
        safetyLevel: "moderado" as SafetyLevel,
        crossContaminationRisk: "medio" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: false,
        isCertified: false,
      },
      {
        id: "lp-d5",
        name: "Pizzas low carb",
        description: "",
        price: 0,
        image: "",
        ingredients: [],
        safetyLevel: "moderado" as SafetyLevel,
        crossContaminationRisk: "medio" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: false,
        isCertified: false,
      },
      {
        id: "lp-d6",
        name: "Marmitas congeladas",
        description: "",
        price: 0,
        image: "",
        ingredients: [],
        safetyLevel: "moderado" as SafetyLevel,
        crossContaminationRisk: "medio" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: false,
        isCertified: false,
      },
    ],
    reviews: [],
  },

  // ── JURO DE DEDINHO ───────────────────────────────────────────
  {
    id: "juro-de-dedinho",
    name: "Juro de Dedinho",
    address: "",
    neighborhood: "",
    city: "Porto Alegre / São Paulo",
    rating: 0,
    reviewCount: 0,
    safetyLevel: "muito_seguro" as SafetyLevel,
    safetyScore: 98,
    image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=400&h=300&fit=crop",
    cuisine: "Doceria / Confeitaria",
    distance: "",
    isOpen: false,
    permanentlyClosed: true,
    isFavorite: false,
    features: ["100% sem glúten", "Sem lactose", "Sem açúcar", "Vegano opção"],
    restrictions: ["Sem glúten", "Sem lactose", "Sem açúcar"],
    safetyProcedures: [
      "Cozinha livre de glúten",
      "Comunicação explícita de segurança para celíacos",
    ],
    description: "Doceria inclusiva com produtos sem glúten, sem lactose e sem açúcar.",
    phone: "",
    website: "https://www.jurodededinho.com.br/",
    dishes: [
      {
        id: "jdd-d1",
        name: "Trufa cookies and cream",
        description: "",
        price: 0,
        image: "",
        ingredients: [],
        safetyLevel: "muito_seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: true,
        isCertified: false,
      },
      {
        id: "jdd-d2",
        name: "Trufa de frutas vermelhas",
        description: "",
        price: 0,
        image: "",
        ingredients: [],
        safetyLevel: "muito_seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: true,
        isCertified: false,
      },
      {
        id: "jdd-d3",
        name: "Trufa de pistache",
        description: "",
        price: 0,
        image: "",
        ingredients: [],
        safetyLevel: "muito_seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: true,
        isCertified: false,
      },
      {
        id: "jdd-d4",
        name: "Brownie",
        description: "",
        price: 0,
        image: "",
        ingredients: [],
        safetyLevel: "muito_seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: true,
        isCertified: false,
      },
      {
        id: "jdd-d5",
        name: "Alfajor",
        description: "",
        price: 0,
        image: "",
        ingredients: [],
        safetyLevel: "muito_seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: true,
        isCertified: false,
      },
      {
        id: "jdd-d6",
        name: "Doces no pote",
        description: "",
        price: 0,
        image: "",
        ingredients: [],
        safetyLevel: "muito_seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: true,
        isCertified: false,
      },
    ],
    reviews: [],
  },

  // ── LIBERA ────────────────────────────────────────────────────
  {
    id: "libera",
    name: "Libera",
    address: "Badenerstrasse 298, 8004 Zürich",
    neighborhood: "",
    city: "Zürich",
    rating: 0,
    reviewCount: 0,
    safetyLevel: "muito_seguro" as SafetyLevel,
    safetyScore: 98,
    image: "https://libera-gf.ch/wp-content/uploads/2026/01/1-scaled.jpg",
    galleryImages: [
      "https://libera-gf.ch/wp-content/uploads/2026/01/1-scaled.jpg",
      "https://libera-gf.ch/wp-content/uploads/2026/01/2-scaled.jpg",
      "https://libera-gf.ch/wp-content/uploads/2026/01/3-scaled.jpg",
      "https://libera-gf.ch/wp-content/uploads/2026/01/4-scaled.jpg",
      "https://libera-gf.ch/wp-content/uploads/2026/01/6-1-scaled.jpg",
    ],
    cuisine: "Café / Bistrô",
    distance: "",
    isOpen: true,
    isFavorite: false,
    features: ["100% sem glúten", "Vegano opção", "Sem lactose opção", "Brunch"],
    restrictions: ["Sem glúten"],
    safetyProcedures: [
      "Proposta criada para atender pessoas que precisam de zero contaminação de glúten",
    ],
    description: "Café e bistrô em Zurique com cardápio sem glúten e foco em segurança.",
    phone: "",
    website: "https://libera-gf.ch/",
    chef: "Marcello Marini e Laura Casalena",
    instagram: "libera.glutenfree",
    dishes: [
      {
        id: "lib-d1",
        name: "Croissants sem glúten",
        description: "",
        price: 0,
        image: "https://libera-gf.ch/wp-content/uploads/2026/01/Progetto-senza-titolo-6-768x768.jpg",
        ingredients: [],
        safetyLevel: "muito_seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: true,
        isCertified: false,
      },
      {
        id: "lib-d2",
        name: "Bowls nutritivos",
        description: "",
        price: 0,
        image: "https://libera-gf.ch/wp-content/uploads/2026/01/6-1-scaled.jpg",
        ingredients: [],
        safetyLevel: "muito_seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: true,
        isCertified: false,
      },
      {
        id: "lib-d3",
        name: "Pratos leves",
        description: "",
        price: 0,
        image: "https://libera-gf.ch/wp-content/uploads/2026/01/7-scaled.jpg",
        ingredients: [],
        safetyLevel: "muito_seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: true,
        isCertified: false,
      },
      {
        id: "lib-d4",
        name: "Opções vegetarianas",
        description: "",
        price: 0,
        image: "https://libera-gf.ch/wp-content/uploads/2026/01/4-scaled.jpg",
        ingredients: [],
        safetyLevel: "muito_seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten", "Vegetariano"],
        isGlutenFree: true,
        isCertified: false,
      },
      {
        id: "lib-d5",
        name: "Opções veganas",
        description: "",
        price: 0,
        image: "https://libera-gf.ch/wp-content/uploads/2026/01/3-scaled.jpg",
        ingredients: [],
        safetyLevel: "muito_seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten", "Vegano"],
        isGlutenFree: true,
        isCertified: false,
      },
    ],
    reviews: [],
  },

  // ── ZUFREEDEN ─────────────────────────────────────────────────
  {
    id: "zufreeden",
    name: "Zufreeden",
    address: "Weinbergstrasse 157, Zürich",
    neighborhood: "",
    city: "Zürich",
    rating: 0,
    reviewCount: 0,
    safetyLevel: "muito_seguro" as SafetyLevel,
    safetyScore: 98,
    image: "https://static.wixstatic.com/media/dca45e_907a60a6de8b4b198dff01e3e1bcd960~mv2.jpg",
    galleryImages: [
      "https://static.wixstatic.com/media/dca45e_907a60a6de8b4b198dff01e3e1bcd960~mv2.jpg",
      "https://static.wixstatic.com/media/dca45e_d6c2c7b7c5634322ab1d3c377712cfe3~mv2.jpg",
      "https://static.wixstatic.com/media/dca45e_41c280ee8cc9471dbc6e1638786bef85~mv2.jpg",
      "https://static.wixstatic.com/media/dca45e_8c9208c5740a41b8b1a76df3ed588892~mv2.jpg",
      "https://static.wixstatic.com/media/dca45e_b56f90979dbe4332a8ceb56e305d34b5~mv2.jpg",
    ],
    cuisine: "Café / Padaria / Confeitaria",
    distance: "",
    isOpen: true,
    isFavorite: false,
    features: ["100% sem glúten", "Padaria artesanal", "Brunch", "Doces"],
    restrictions: ["Sem glúten"],
    safetyProcedures: [
      "Ingredientes, ambiente e equipamentos dedicados ao preparo seguro para celíacos",
    ],
    description: "Café e padaria artesanal com operação 100% sem glúten.",
    phone: "",
    website: "https://www.zufreeden.ch/",
    chef: "Bronwyn e Siobhan",
    instagram: "zufreeden_glutenfree.zurich",
    dishes: [
      {
        id: "zuf-d1",
        name: "Pão de trigo sarraceno",
        description: "",
        price: 0,
        image: "https://static.wixstatic.com/media/dca45e_907a60a6de8b4b198dff01e3e1bcd960~mv2.jpg",
        ingredients: [],
        safetyLevel: "muito_seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: true,
        isCertified: false,
      },
      {
        id: "zuf-d2",
        name: "Pretzels",
        description: "",
        price: 0,
        image: "https://static.wixstatic.com/media/dca45e_d6c2c7b7c5634322ab1d3c377712cfe3~mv2.jpg",
        ingredients: [],
        safetyLevel: "muito_seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: true,
        isCertified: false,
      },
      {
        id: "zuf-d3",
        name: "Sanduíches",
        description: "",
        price: 0,
        image: "https://static.wixstatic.com/media/dca45e_8c9208c5740a41b8b1a76df3ed588892~mv2.jpg",
        ingredients: [],
        safetyLevel: "muito_seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: true,
        isCertified: false,
      },
      {
        id: "zuf-d4",
        name: "Quiches",
        description: "",
        price: 0,
        image: "https://static.wixstatic.com/media/dca45e_4db0f69f609c4f10bd85f3b4647b0055~mv2.jpg",
        ingredients: [],
        safetyLevel: "muito_seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: true,
        isCertified: false,
      },
      {
        id: "zuf-d5",
        name: "Brownies",
        description: "",
        price: 0,
        image: "https://static.wixstatic.com/media/dca45e_b56f90979dbe4332a8ceb56e305d34b5~mv2.jpg",
        ingredients: [],
        safetyLevel: "muito_seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: true,
        isCertified: false,
      },
      {
        id: "zuf-d6",
        name: "Cheesecake",
        description: "",
        price: 0,
        image: "https://static.wixstatic.com/media/dca45e_cc9d6be0ab8e445590943caf04bd089b~mv2.jpg",
        ingredients: [],
        safetyLevel: "muito_seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: true,
        isCertified: false,
      },
      {
        id: "zuf-d7",
        name: "Pão de banana",
        description: "",
        price: 0,
        image: "https://static.wixstatic.com/media/dca45e_41c280ee8cc9471dbc6e1638786bef85~mv2.jpg",
        ingredients: [],
        safetyLevel: "muito_seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: true,
        isCertified: false,
      },
    ],
    reviews: [],
  },

  // ── À VIE BAKED GOODS ─────────────────────────────────────────
  {
    id: "a-vie",
    name: "À VIE Baked Goods",
    address: "Zelgstrasse 13, 8003 Zürich",
    neighborhood: "",
    city: "Zürich",
    rating: 0,
    reviewCount: 0,
    safetyLevel: "muito_seguro" as SafetyLevel,
    safetyScore: 98,
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&h=400&fit=crop",
    galleryImages: [
      "https://aviebakedgoods.com/wp-content/uploads/2025/10/a-Vie_17102025_2042-scaled.jpg",
    ],
    cuisine: "Confeitaria / Padaria",
    distance: "",
    isOpen: true,
    isFavorite: false,
    features: ["100% sem glúten", "Patisserie", "Premium", "Doces"],
    restrictions: ["Sem glúten"],
    safetyProcedures: [
      "Negócio criado a partir de experiência real com doença celíaca",
      "Foco em segurança e sofisticação",
    ],
    description: "Patisserie artesanal em Zurique com produtos sem glúten inspirados na confeitaria francesa.",
    phone: "+41 76 376 05 02",
    email: "contact@aviebakedgoods.com",
    website: "https://aviebakedgoods.com/",
    chef: "Bettina Meier-Bickel",
    dishes: [
      {
        id: "avie-d1",
        name: "Brioches artesanais",
        description: "",
        price: 0,
        image: "https://aviebakedgoods.com/wp-content/uploads/2025/10/a-Vie_17102025_2042-scaled.jpg",
        ingredients: [],
        safetyLevel: "muito_seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: true,
        isCertified: false,
      },
      {
        id: "avie-d2",
        name: "Tortas francesas",
        description: "",
        price: 0,
        image: "https://aviebakedgoods.com/wp-content/uploads/2025/10/a-Vie_17102025_1119-scaled.jpg",
        ingredients: [],
        safetyLevel: "muito_seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: true,
        isCertified: false,
      },
      {
        id: "avie-d3",
        name: "Pâtisserie moderna",
        description: "",
        price: 0,
        image: "",
        ingredients: [],
        safetyLevel: "muito_seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: true,
        isCertified: false,
      },
      {
        id: "avie-d4",
        name: "Doces refinados",
        description: "",
        price: 0,
        image: "",
        ingredients: [],
        safetyLevel: "muito_seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: true,
        isCertified: false,
      },
    ],
    reviews: [],
  },

  // ── JACKIE'S ──────────────────────────────────────────────────
  {
    id: "jackies",
    name: "Jackie's",
    address: "Kemptpark 13, 8310 Kemptthal",
    neighborhood: "",
    city: "Kemptthal",
    rating: 0,
    reviewCount: 0,
    safetyLevel: "muito_seguro" as SafetyLevel,
    safetyScore: 98,
    image: "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=600&h=400&fit=crop",
    galleryImages: [
      "https://jackies.ch/wp-content/uploads/2021/08/Brote-1024x640.jpg",
      "https://jackies.ch/wp-content/uploads/2025/02/01_Nussbrot-1-1024x768.jpg",
      "https://jackies.ch/wp-content/uploads/2021/11/01_Zopfball-Maxi-1024x768.jpg",
      "https://jackies.ch/wp-content/uploads/2021/07/02_Apfelstreuseltoertli-1024x768.jpg",
      "https://jackies.ch/wp-content/uploads/2024/06/Himbeerkuchen_ganz_Web-1.jpg",
    ],
    cuisine: "Padaria / Confeitaria",
    distance: "",
    isOpen: true,
    isFavorite: false,
    features: ["100% sem glúten", "Padaria artesanal", "Congelados", "Vegano opção"],
    restrictions: ["Sem glúten"],
    safetyProcedures: [
      "Produção dedicada e receitas próprias",
      "Foco em consumo seguro em casa ou para levar",
    ],
    description: "Padaria artesanal com produção totalmente sem glúten e produtos para o dia a dia.",
    phone: "",
    email: "info@jackies.ch",
    website: "https://jackies.ch/",
    chef: "Jacqueline Bättig",
    instagram: "jackies_glutenfrei",
    dishes: [
      {
        id: "jck-d1",
        name: "Pães artesanais sem glúten",
        description: "",
        price: 0,
        image: "https://jackies.ch/wp-content/uploads/2025/02/01_Nussbrot-1-1024x768.jpg",
        ingredients: [],
        safetyLevel: "muito_seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: true,
        isCertified: false,
      },
      {
        id: "jck-d2",
        name: "Doces tradicionais adaptados",
        description: "",
        price: 0,
        image: "https://jackies.ch/wp-content/uploads/2024/06/HimbeerKuchen_Stueck_Web.jpg",
        ingredients: [],
        safetyLevel: "muito_seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: true,
        isCertified: false,
      },
      {
        id: "jck-d3",
        name: "Produtos congelados",
        description: "",
        price: 0,
        image: "https://jackies.ch/wp-content/uploads/2021/11/01_Zopfball-Maxi-1024x768.jpg",
        ingredients: [],
        safetyLevel: "muito_seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: true,
        isCertified: false,
      },
    ],
    reviews: [],
  },

  // ── GRANÒ ─────────────────────────────────────────────────────
  {
    id: "grano",
    name: "Granò",
    address: "Badenerstrasse 298, 8004 Zürich",
    neighborhood: "",
    city: "Zürich",
    rating: 0,
    reviewCount: 0,
    safetyLevel: "muito_seguro" as SafetyLevel,
    safetyScore: 98,
    image: "https://images.unsplash.com/photo-1571997478779-2adcbbe9ab2f?w=600&h=400&fit=crop",
    galleryImages: [
      "https://cdn.prod.website-files.com/6475bde4c3f3fd0a9eacd1e2/66167708e3240851a86de032_IMG_1914.jpeg",
      "https://cdn.prod.website-files.com/6475bde4c3f3fd0a9eacd1e2/66167705fd3933467956712f_IMG_1918.jpeg",
      "https://cdn.prod.website-files.com/6475bde4c3f3fd0a9eacd1e2/66167707037c4d86fcfaf398_IMG_2022.jpeg",
      "https://cdn.prod.website-files.com/6475bde4c3f3fd0a9eacd1e2/6490b83db0bc0a989543c260_b1.jpg",
      "https://cdn.prod.website-files.com/6475bde4c3f3fd0a9eacd1e2/66167707fd3933467956724d_IMG_1898.jpeg",
    ],
    cuisine: "Restaurante Italiano / Pizzaria",
    distance: "",
    isOpen: true,
    isFavorite: false,
    features: ["100% sem glúten", "Italiano", "Pizza", "Sem lactose opção"],
    restrictions: ["Sem glúten"],
    safetyProcedures: [
      "Cozinha dedicada e forno exclusivo",
      "Operação sem risco de contaminação cruzada",
    ],
    description: "Restaurante italiano em Zurique com cozinha 100% sem glúten.",
    phone: "+41 44 401 11 99",
    email: "info@gra-no.ch",
    website: "https://www.gra-no.ch/english",
    chef: "Marcello Marini e Laura Casalena",
    instagram: "grano_zurich",
    dishes: [
      {
        id: "grano-d1",
        name: "Pizzas italianas clássicas",
        description: "",
        price: 0,
        image: "https://cdn.prod.website-files.com/6475bde4c3f3fd0a9eacd1e2/649198088b5eab49d8f8834b_Marinara.png",
        ingredients: [],
        safetyLevel: "muito_seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: true,
        isCertified: false,
      },
      {
        id: "grano-d2",
        name: "Pizzas especiais da semana",
        description: "",
        price: 0,
        image: "https://cdn.prod.website-files.com/6475bde4c3f3fd0a9eacd1e2/6490b83a95392241cab77caa_a1.jpg",
        ingredients: [],
        safetyLevel: "muito_seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: true,
        isCertified: false,
      },
      {
        id: "grano-d3",
        name: "Sobremesas italianas",
        description: "",
        price: 0,
        image: "https://cdn.prod.website-files.com/6475bde4c3f3fd0a9eacd1e2/66167707fd3933467956724d_IMG_1898.jpeg",
        ingredients: [],
        safetyLevel: "muito_seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: true,
        isCertified: false,
      },
      {
        id: "grano-d4",
        name: "Cervejas sem glúten",
        description: "",
        price: 0,
        image: "https://cdn.prod.website-files.com/6475bde4c3f3fd0a9eacd1e2/66167709b55b0ad950ed7fa2_IMG_2024.jpeg",
        ingredients: [],
        safetyLevel: "muito_seguro" as SafetyLevel,
        crossContaminationRisk: "baixo" as const,
        restrictions: ["Sem glúten"],
        isGlutenFree: true,
        isCertified: false,
      },
    ],
    reviews: [],
  },
];

export const mockDishes = [
  {
    id: "dd1",
    name: "Marguerita",
    restaurantName: "Pizza For Fun",
    restaurantId: "pizza-for-fun",
    dishId: "pff-d1",
    rating: 4.9,
    image: "https://pizzaforfun.com.br/wp-content/uploads/2021/05/Marguerita-For-Fun@2x-1200x853.jpg",
  },
  {
    id: "dd2",
    name: "Pão tipo francês",
    restaurantName: "Grão Fino",
    restaurantId: "grao-fino",
    dishId: "grao-fino-d1",
    rating: 4.8,
    image: "https://static.wixstatic.com/media/4614e6_03405cb3563f4c609004d49cfa59a3c2~mv2.jpg",
  },
  {
    id: "dd3",
    name: "Tarte de framboesa",
    restaurantName: "Jackie's",
    restaurantId: "jackies",
    dishId: "jck-d2",
    rating: 4.9,
    image: "https://jackies.ch/wp-content/uploads/2024/06/HimbeerKuchen_Stueck_Web.jpg",
  },
  {
    id: "dd4",
    name: "Bowl nutritivo",
    restaurantName: "Libera",
    restaurantId: "libera",
    dishId: "lib-d2",
    rating: 4.8,
    image: "https://libera-gf.ch/wp-content/uploads/2026/01/6-1-scaled.jpg",
  },
  {
    id: "dd5",
    name: "Pizza Marinara",
    restaurantName: "Granò",
    restaurantId: "grano",
    dishId: "grano-d1",
    rating: 4.9,
    image: "https://cdn.prod.website-files.com/6475bde4c3f3fd0a9eacd1e2/649198088b5eab49d8f8834b_Marinara.png",
  },
  {
    id: "dd6",
    name: "Brioches artesanais",
    restaurantName: "À VIE Baked Goods",
    restaurantId: "a-vie",
    dishId: "avie-d1",
    rating: 4.7,
    image: "https://aviebakedgoods.com/wp-content/uploads/2025/10/a-Vie_17102025_2042-scaled.jpg",
  },
];

export function localizeDish(dish: Dish, restaurantId: string, lang: Language): Dish {
  if (lang !== "en") return dish;
  const tr = restaurantTranslationsEn[restaurantId]?.dishes?.[dish.id];
  if (!tr) return dish;
  return {
    ...dish,
    ...(tr.name !== undefined && { name: tr.name }),
    ...(tr.description !== undefined && { description: tr.description }),
    ...(tr.ingredients !== undefined && { ingredients: tr.ingredients }),
    ...(tr.adaptations !== undefined && { adaptations: tr.adaptations }),
    ...(tr.restrictions !== undefined && { restrictions: tr.restrictions }),
    ...(tr.crossContaminationPrep !== undefined && { crossContaminationPrep: tr.crossContaminationPrep }),
  };
}

export function localizeReview(review: Review, restaurantId: string, lang: Language): Review {
  if (lang !== "en") return review;
  const tr = restaurantTranslationsEn[restaurantId]?.reviews?.[review.id];
  if (!tr) return review;
  return {
    ...review,
    ...(tr.tags !== undefined && { tags: tr.tags }),
    ...(tr.comment !== undefined && { comment: tr.comment }),
  };
}

export function localizeRestaurant(restaurant: Restaurant, lang: Language): Restaurant {
  if (lang !== "en") return restaurant;
  const tr = restaurantTranslationsEn[restaurant.id];
  return {
    ...restaurant,
    ...(tr?.city !== undefined && { city: tr.city }),
    ...(tr?.cuisine !== undefined && { cuisine: tr.cuisine }),
    ...(tr?.description !== undefined && { description: tr.description }),
    ...(tr?.openingHours !== undefined && { openingHours: tr.openingHours }),
    ...(tr?.features !== undefined && { features: tr.features }),
    ...(tr?.restrictions !== undefined && { restrictions: tr.restrictions }),
    ...(tr?.safetyProcedures !== undefined && { safetyProcedures: tr.safetyProcedures }),
    dishes: restaurant.dishes.map((d) => localizeDish(d, restaurant.id, lang)),
    reviews: restaurant.reviews.map((r) => localizeReview(r, restaurant.id, lang)),
  };
}

export function localizeSafetyLevelConfig(
  lang: Language
): Record<SafetyLevel, { label: string; color: string; bg: string; description: string }> {
  if (lang !== "en") return safetyLevelConfig;
  const result = {} as Record<SafetyLevel, { label: string; color: string; bg: string; description: string }>;
  (Object.keys(safetyLevelConfig) as SafetyLevel[]).forEach((key) => {
    const base = safetyLevelConfig[key];
    const tr = safetyLevelLabelsEn[key];
    result[key] = {
      ...base,
      ...(tr?.label !== undefined && { label: tr.label }),
      ...(tr?.description !== undefined && { description: tr.description }),
    };
  });
  return result;
}

export const safetyFilters = [
  { id: "muito_seguro", label: "Muito seguro", icon: "🛡️" },
  { id: "sem_gluten_100", label: "100% sem glúten", icon: "✅" },
  { id: "protocolo_rigoroso", label: "Protocolo rigoroso", icon: "🔒" },
  { id: "comunidade", label: "Indicado pela comunidade", icon: "❤️" },
];
